<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="assembly_table" params="parent">
    <xacro:arg name="table_size" default="1.5"/>
  <!-- CHANGED TO ACCOUNT FOR KUKA IIWA -->
  <xacro:property name="BASE_PLATE_THICKNESS" value="0.6096" scope="parent"/>
  <xacro:property name="BASE_PLATE_LENGTH" value="0.762" scope="parent"/>
  <xacro:property name="BASE_PLATE_WIDTH" value="0.3048" scope="parent"/>

    <link name="table">
      <visual>
        <origin xyz="0 0 -0.10"/>
        <geometry>
          <box size="$(arg table_size) $(arg table_size) 0.05"/>
        </geometry>
        <material name="StainlessSteel">
          <color rgba="0.8 0.8 0.8 0.9"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 -0.05"/>
        <geometry>
          <box size="$(arg table_size) $(arg table_size) 0.1"/>
        </geometry>
      </collision>
    </link>

    <joint name="${parent}_to_table_joint" type="fixed">
<!--      <origin xyz="0 0 1.0"/>-->
      <origin xyz="0 0 0.0"/>
      <parent link="${parent}"/>
      <child link="table"/>
    </joint>

    <link name="base_plate">
      <visual>
        <origin xyz="${0.5 * BASE_PLATE_WIDTH} ${0.5 * BASE_PLATE_LENGTH} ${BASE_PLATE_THICKNESS * 0.5}"/>
        <geometry>
          <box size="${BASE_PLATE_WIDTH} ${BASE_PLATE_LENGTH} ${BASE_PLATE_THICKNESS}"/>
        </geometry>
        <material name="StainlessSteel">
          <color rgba="0.6 0.1 0.1 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="${0.5 * BASE_PLATE_WIDTH} ${0.5 * BASE_PLATE_LENGTH} ${BASE_PLATE_THICKNESS}"/>
        <geometry>
          <box size="${BASE_PLATE_WIDTH} ${BASE_PLATE_LENGTH} ${BASE_PLATE_THICKNESS}"/>
        </geometry>
        <material name="StainlessSteel">
          <color rgba="0.6 0.1 0.1 1.0"/>
        </material>
      </collision>
    </link>

    <joint name="table_to_base_plate" type="fixed">
      <origin xyz="${-0.5*$(arg table_size) + 0.1397 } ${-0.5*$(arg table_size) + 0.09525} 0.0" rpy="0 0 0"/>
       <parent link="table"/>
       <child link="base_plate"/>
    </joint>
  </xacro:macro>
</robot>
