#Config info needed for the hardware/software combination running Conntact.
#We're running on a UR10e on a specific computer, so we need to tweak these
#params to work well in our cell.
framework: # Params to keep the data pipeline reliable
  refresh_rate: 100 #Algorithm loop execution frequency, in hz
robot: # Params to keep the robot safe and reliable
  speed_static: [.001, .001, .001]
  force_setpoints:
    direct: # Force at the gripper base
      warning: [40, 40, 40]   # Force value which pauses the program. Rel. to gripper.
      dangerous: [55, 55, 65] # Force value which kills the program. Rel. to gripper.
    transverse: # Force at the TCP creating torques. Values are in `force/mm of tcp length`
      warning: [20, 20, 20]   # Force value which pauses the program.
      dangerous: [30, 30, 30] # Force value which kills the program.
    max_error: [4, 4, 4]
