objects: #List objects and their required description
    peg_10mm:
        stl_file: "file_location.stl"
        local_position: [36.5, -202, 7.5] #Starting position from kitting_frame
        local_orientation: [90, 0, 0]     #rotations about new relative axes
        dimensions:
            diameter: 10 #mm
            length: 50 #mm
            min_insertion_depth: 7.5 #mm : minimum depth the item must insert before considering job complete; "feeling" it stop is the end condition
        tolerance:
            upper_tolerance:  0.00 #e.g., h7 (ISO 286)
            lower_tolerance:  -0.01 #e.g., h7 (ISO 286)
        material: "stainless steel"
        grasping:
            pinch_grasping: #For pinch gripper being used on the demo. True for shafts, false for fixed pegs
                default_ properties:
                    grasp_pressure: 50 #Percent maximum force
                    #friction: #Unsure how to format this. Should we assume the user has chosen grasps that have sufficient friction cones to control the graspable part?
                locations:
                    - pose: [1, 2, 3] #Coordinate transformation relative to peg/hole local_part_pose being grasped
                      grasp_name: "tip"
                      part_grasp_pose: [1, 2, 3] #transformation relative to local_part_pose
                      gripper_grasp_pose: [1, 2, 3] #transformation relative to local_part_pose. Robot solves path planning to reach this cartesian position
                      grasp_pressure: 50 #Percent maximum force
                      #friction: #Unsure how to format this. Should we assume the user has chosen grasps that have sufficient friction cones to control the graspable part?
                    - pose: [1, 2, 3] #Coordinate transformation relative to peg/hole local_part_pose being grasped
                      grasp_name: "middle"
                      part_grasp_pose: [1, 2, 3] #transformation relative to local_part_pose
                      gripper_grasp_pose: [1, 2, 3] #transformation relative to local_part_pose. Robot solves path planning to reach this cartesian position
                      grasp_pressure: 50 #Percent maximum force
                      #friction: #Unsure how to format this. Should we assume the user has chosen grasps that have sufficient friction cones to control the graspable part?
    hole_10mm:
        stl_file: "file_location.stl"
        local_position: [264, -41.3, 0] #Starting position from task_frame
        local_orientation: [0,0,0]
        dimensions:
            diameter: 10.4 #mm
            depth: 20 #mm
        tolerance:
            upper_tolerance:  0.01 #e.g., H7 (ISO 286)
            lower_tolerance:  0.00 #e.g., H7 (ISO 286)
        material: "stainless steel"
    peg_8mm:
        stl_file: "file_location.stl"
        local_position: [36.5, -202, 4] #TODO:_Get real values #Starting position from kitting_frame
        local_orientation: [90, 0, 0]   #TODO: Get real values  #rotations about new relative axes
        dimensions:
            diameter: 8 #mm
            length: 50 #mm
            min_insertion_depth: 7.5 #mm : minimum depth the item must insert before considering job complete; "feeling" it stop is the end condition
        tolerance:
            upper_tolerance:  0.00 #mm, e.g., h7 (ISO 286)
            lower_tolerance:  -0.05 #mm, e.g., h7 (ISO 286)
        material: "stainless steel"
        grasping:
            pinch_grasping: #For pinch gripper being used on the demo. True for shafts, false for fixed pegs
                default_ properties:
                    grasp_pressure: 50 #Percent maximum force
                    #friction: #Unsure how to format this. Should we assume the user has chosen grasps that have sufficient friction cones to control the graspable part?
                locations:
                    - pose: [50, 0, 0] #Coordinate transformation relative to peg/hole local_part_pose being grasped
                      grasp_name: "tip"
                      part_grasp_pose: [1, 2, 3] #transformation relative to local_part_pose
                      gripper_grasp_pose: [1, 2, 3] #transformation relative to local_part_pose. Robot solves path planning to reach this cartesian position
                      grasp_pressure: 50 #Percent maximum force
                      #friction: #Unsure how to format this. Should we assume the user has chosen grasps that have sufficient friction cones to control the graspable part?
                    - pose: [25, 0, 0] #Coordinate transformation relative to peg/hole local_part_pose being grasped
                      grasp_name: "middle"
                      part_grasp_pose: [1, 2, 3] #transformation relative to local_part_pose
                      gripper_grasp_pose: [1, 2, 3] #transformation relative to local_part_pose. Robot solves path planning to reach this cartesian position
                      grasp_pressure: 50 #Percent maximum force
                      #friction: #Unsure how to format this. Should we assume the user has chosen grasps that have sufficient friction cones to control the graspable part?
    hole_8mm:
        stl_file: "file_location.stl"
        local_position: [36, -116, 0] #Starting position from task_frame
        local_orientation: [0,0,0]
        dimensions:
            diameter: 8.4 #mm
            depth: 20 #mm
        tolerance:
            upper_tolerance:  0.01 #e.g., H7 (ISO 286)
            lower_tolerance:  0.00 #e.g., H7 (ISO 286)
        material: "stainless steel"
    peg_4mm:
        stl_file: "file_location.stl"
        local_position: [36.5, -202, 2] #TODO:_Get real values #Starting position from kitting_frame
        local_orientation: [90, 0, 0]   #TODO: Get real values  #rotations about new relative axes
        dimensions:
            diameter: 3.5 #mm
            length: 50 #mm
            min_insertion_depth: 7.5 #mm : minimum depth the item must insert before considering job complete; "feeling" it stop is the end condition
        tolerance:
            upper_tolerance:  0.00 #mm, e.g., h7 (ISO 286)
            lower_tolerance:  -0.05 #mm, e.g., h7 (ISO 286)
        material: "stainless steel"
        grasping:
            pinch_grasping: #For pinch gripper being used on the demo. True for shafts, false for fixed pegs
                default_ properties:
                    grasp_pressure: 50 #Percent maximum force
                    #friction: #Unsure how to format this. Should we assume the user has chosen grasps that have sufficient friction cones to control the graspable part?
                locations:
                    - pose: [50, 0, 0] #Coordinate transformation relative to peg/hole local_part_pose being grasped
                      grasp_name: "tip"
                      part_grasp_pose: [1, 2, 3] #transformation relative to local_part_pose
                      gripper_grasp_pose: [1, 2, 3] #transformation relative to local_part_pose. Robot solves path planning to reach this cartesian position
                      grasp_pressure: 50 #Percent maximum force
                      #friction: #Unsure how to format this. Should we assume the user has chosen grasps that have sufficient friction cones to control the graspable part?
                    - pose: [25, 0, 0] #Coordinate transformation relative to peg/hole local_part_pose being grasped
                      grasp_name: "middle"
                      part_grasp_pose: [1, 2, 3] #transformation relative to local_part_pose
                      gripper_grasp_pose: [1, 2, 3] #transformation relative to local_part_pose. Robot solves path planning to reach this cartesian position
                      grasp_pressure: 50 #Percent maximum force
                      #friction: #Unsure how to format this. Should we assume the user has chosen grasps that have sufficient friction cones to control the graspable part?
    hole_4mm:
        stl_file: "file_location.stl"
        local_position: [37, -191, 0] #Starting position from task_frame
        local_orientation: [0,0,0]
        dimensions:
            diameter: 3.7 #mm
            depth: 20 #mm
        tolerance:
            upper_tolerance:  0.01 #e.g., H7 (ISO 286)
            lower_tolerance:  0.00 #e.g., H7 (ISO 286)
        material: "stainless steel"
    peg_16mm:
        stl_file: "file_location.stl"
        local_position: [36.5, -202, 8] #TODO:_Get real values #Starting position from kitting_frame
        local_orientation: [90, 0, 0]   #TODO: Get real values  #rotations about new relative axes
        dimensions:
            diameter: 16 #mm
            length: 50 #mm
            min_insertion_depth: 7.5 #mm : minimum depth the item must insert before considering job complete; "feeling" it stop is the end condition
        tolerance:
            upper_tolerance:  0.00 #mm, e.g., h7 (ISO 286)
            lower_tolerance:  -0.05 #mm, e.g., h7 (ISO 286)
        material: "stainless steel"
        grasping:
            pinch_grasping: #For pinch gripper being used on the demo. True for shafts, false for fixed pegs
                default_ properties:
                    grasp_pressure: 50 #Percent maximum force
                    #friction: #Unsure how to format this. Should we assume the user has chosen grasps that have sufficient friction cones to control the graspable part?
                locations:
                    - pose: [50, 0, 0] #Coordinate transformation relative to peg/hole local_part_pose being grasped
                      grasp_name: "tip"
                      part_grasp_pose: [1, 2, 3] #transformation relative to local_part_pose
                      gripper_grasp_pose: [1, 2, 3] #transformation relative to local_part_pose. Robot solves path planning to reach this cartesian position
                      grasp_pressure: 50 #Percent maximum force
                      #friction: #Unsure how to format this. Should we assume the user has chosen grasps that have sufficient friction cones to control the graspable part?
                    - pose: [25, 0, 0] #Coordinate transformation relative to peg/hole local_part_pose being grasped
                      grasp_name: "middle"
                      part_grasp_pose: [1, 2, 3] #transformation relative to local_part_pose
                      gripper_grasp_pose: [1, 2, 3] #transformation relative to local_part_pose. Robot solves path planning to reach this cartesian position
                      grasp_pressure: 50 #Percent maximum force
                      #friction: #Unsure how to format this. Should we assume the user has chosen grasps that have sufficient friction cones to control the graspable part?
    hole_16mm:
        stl_file: "file_location.stl"
        local_position: [262, -266, 0] #Starting position from task_frame
        local_orientation: [0,0,0]
        dimensions:
            diameter: 16.4 #mm
            depth: 20 #mm
        tolerance:
            upper_tolerance:  0.01 #e.g., H7 (ISO 286)
            lower_tolerance:  0.00 #e.g., H7 (ISO 286)
        material: "stainless steel"
environment_state:
    task_frame:
        position: [266, -137, -455]
        orientation: [0, 0, 0]
    kitting_frame:
        position: [640, 544, -502]
        orientation: [0, 0, 0]
assembled_state: #List the desired assembled state
    peg:
        position: [1, 2, 3] #Trasformation from peg.local_part_pose relative to chosen Newtonian inertial frame
    hole: 
        position: [1, 2, 3] #Transformation from hole.local_part_pose relative to chosen Newtonian inertial frame